# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Install Dependencies and Build Webpack
        run: 
          npm install
          npm run build
      - name: Upload Webpack Build Artifacts
      - uses: actions/upload-artifact@v4
        with: 
          name: webpack-artificats
          path: public/
  #Upload the artifacts from workflow allowing data between jobs and store data. . 

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
        #See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Download Webpack Build Artifacts
    - uses: actions/download-artifact@v4
      with: 
          name: webpack-artificats
          path: public
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install -g npm
        npm install
        npm install --save-dev @babel/preset-env
        npm update
        npm test -- -u
           
      env:
        CI: true
